<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\EvenTech.BE\EvenTech.BE.csproj" />
    <ProjectReference Include="..\EvenTech.Services\EvenTech.Services.csproj" />
    <ProjectReference Include="..\EvenTech.DAL\EvenTech.DAL.csproj" />
    <ProjectReference Include="..\EvenTech.BLL\EvenTech.BLL.csproj" />
  </ItemGroup>
</Project>
